# -*- coding: utf-8 -*-
"""cv_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q3maSwSgxx44sRdZtgGCNz2SF9cxF3gt
"""

#mount drive
from google.colab import drive
drive.mount('/content/drive')

#paths
import pandas as pd
import os
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras import layers, Model


data_dir = "/content/drive/MyDrive/dataset"
csv_path = data_dir + "/ham10000_metadata_2025-03-28.csv"
img_dir = data_dir + "/ISIC-images"

#load csv
df = pd.read_csv("/content/drive/MyDrive/dataset/ham10000_metadata_2025-03-28.csv")

# Keep required features
df = df[['isic_id', 'benign_malignant', 'age_approx', 'anatom_site_general']]

# Add filename and full filepath
df['filename'] = df['isic_id'] + ".jpg"
df['filepath'] = df['filename'].apply(lambda x: os.path.join(img_dir, x))

#preprocessing

# Fill NaN numeric values
df['age_approx'] = df['age_approx'].fillna(df['age_approx'].median())

# Fill missing text values
df['anatom_site_general'] = df['anatom_site_general'].fillna("unknown")
df['benign_malignant'] = df['benign_malignant'].fillna("benign")

# Keep only rows where image exists
df = df[df['filepath'].apply(os.path.exists)]

# Drop any remaining NaN just to be safe
df = df.dropna()

print("Cleaned rows:", len(df))

#train test split
train_df, test_df = train_test_split(
    df, test_size=0.2, stratify=df['benign_malignant'], random_state=42
)
train_df, val_df = train_test_split(
    train_df, test_size=0.1, stratify=train_df['benign_malignant'], random_state=42
)

print("Train:", len(train_df))
print("Val:", len(val_df))
print("Test:", len(test_df))

#image data generators
IMG_SIZE = 224
BATCH = 32

train_gen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=20,
    zoom_range=0.2,
    horizontal_flip=True
).flow_from_dataframe(
    train_df,
    x_col='filepath',
    y_col='benign_malignant',
    target_size=(IMG_SIZE, IMG_SIZE),
    class_mode='binary',
    batch_size=BATCH
)

val_gen = ImageDataGenerator(rescale=1./255).flow_from_dataframe(
    val_df,
    x_col='filepath',
    y_col='benign_malignant',
    target_size=(IMG_SIZE, IMG_SIZE),
    class_mode='binary',
    batch_size=BATCH
)

test_gen = ImageDataGenerator(rescale=1./255).flow_from_dataframe(
    test_df,
    x_col='filepath',
    y_col='benign_malignant',
    target_size=(IMG_SIZE, IMG_SIZE),
    class_mode='binary',
    batch_size=BATCH,
    shuffle=False
)

print("✓ Preprocessing successful!")

#model

from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras import layers, Model

# Load base model
base = MobileNetV2(weights="imagenet", include_top=False, input_shape=(224, 224, 3))
base.trainable = False  # Freeze base model

# Add classification layers
x = layers.GlobalAveragePooling2D()(base.output)
x = layers.Dense(64, activation='relu')(x)
x = layers.Dropout(0.3)(x)
output = layers.Dense(1, activation='sigmoid')(x)

model = Model(inputs=base.input, outputs=output)

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.summary()

# train
history = model.fit(
    train_gen,
    validation_data=val_gen,
    epochs=10
)

#evaluation
loss, accuracy = model.evaluate(test_gen)
print("Test Accuracy:", accuracy)
print("Test Loss:", loss)

from sklearn.metrics import confusion_matrix, classification_report
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Get predictions
test_gen.reset()
pred = model.predict(test_gen)
pred_labels = (pred > 0.5).astype(int)

true_labels = test_gen.classes

# Confusion Matrix
cm = confusion_matrix(true_labels, pred_labels)

plt.figure(figsize=(6, 5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Benign', 'Malignant'],
            yticklabels=['Benign', 'Malignant'])
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

# Classification Report
print(classification_report(true_labels, pred_labels, target_names=['Benign', 'Malignant']))

from sklearn.metrics import roc_curve, auc

fpr, tpr, _ = roc_curve(true_labels, pred)
roc_auc = auc(fpr, tpr)

plt.figure(figsize=(6,5))
plt.plot(fpr, tpr, label="AUC = {:.4f}".format(roc_auc))
plt.plot([0,1], [0,1], 'k--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend()
plt.show()

#image prediction
import numpy as np
from tensorflow.keras.preprocessing import image
from google.colab import files
import matplotlib.pyplot as plt

uploaded = files.upload()

for fn in uploaded.keys():
    print("\nProcessing:", fn)

    # Load & preprocess
    img = image.load_img(fn, target_size=(224, 224))
    img_array = image.img_to_array(img) / 255.0
    img_array = np.expand_dims(img_array, axis=0)

    # Predict
    prediction = model.predict(img_array)[0][0]

    # Display image
    plt.imshow(img)
    plt.axis("off")
    plt.show()

    # Label
    if prediction > 0.5:
        print("Prediction:", "Malignant (Cancer)")
    else:
        print("Prediction:", "Benign (Non-cancer)")

    print("Raw Score:", float(prediction))